@WordApp.Core_HostAddress = http://localhost:5093

GET https://localhost:7207/api/Vocable/GetAllAsync
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzcyN2JiY2NlMWRiOGIyM2M4YmQwNmQiLCJlbWFpbCI6Im9ndXpAZ21haWwuY29tIiwianRpIjoiZDQ4MjRlYjMtMDQyMy00OGY5LTgyMjEtYTVkNzExMzNhMjdhIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Im9ndXoiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTczNTU2NTg2OCwiaXNzIjoieW91cmlzc3VlciIsImF1ZCI6InlvdXJhdWRpZW5jZSJ9.MejYPMJsxknVXvTM1pcfEd0Ci7YXTCF6woLJwJkE84g
Accept: application/json





###
